sudo: required 
language: node_js
node_js:
    - 17
    
services: 
    - docker
before_install: 
    - docker build -t react-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true react-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "react-app" 
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-026376606405" 
  bucket_path: "EBApptest" 
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"